### ISSUE TITLE
DecorrelatedJitterBackoffV2 returns negative TimeSpan with large number of retries

### ISSUE THREAD

**Issue by tonycoelho** [Polly-Contrib/Polly.Contrib.WaitAndRetry#24] opened 2020-04-22 17:31 UTC
When using DecorrelatedJitterBackoffV2 with a large number of retries (i.e. 50), the formula starts returning negative TimeSpans. This is due to the _prev_ value being larger than _next_.

**Expected behavior**: 
DecorrelatedJitterBackoffV2 should never return an negative TimeSpan
<br/>

**Actual behaviour**:
DecorrelatedJitterBackoffV2 returns a negative TimeSpan after a large number of retries
<br/>

**Steps / Code to reproduce the problem**: 
See the following c# fiddle for steps to reproduce:
https://dotnetfiddle.net/fAWqnz

**Comment by reisenberger** [comment] 2020-05-02 13:40
Thanks for raising this and for the exemplary clear repro.  

The issue was not caused by `prev > next`, but by truncation in a conversion of `double` to `long`, as described at: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/numeric-conversions .  Next release will fix.

You would have had other problems before hitting this in production, though.  To overflow `TimeSpan.MaxValue`, the timespans generated must be in the order of millenia. The number of retries configured (50 or 100) with a formula which [intentionally has an (average) 2^n exponential characteristic](https://github.com/Polly-Contrib/Polly.Contrib.WaitAndRetry#new-jitter-recommendation) naturally generates such large values. For instance, from one example run of the DotNetFiddle, the iteration value prior to overflowing was ~17 thousand years. On the assumption you don't want delays-before-retrying to be that long :wink:, but you do need up to 50 retries, you may need to tweak the jitter formula.

`DecorrelatedJitterBackoffV2(...)` just returns an `IEnumerable<TimeSpan>`, so it is easy to onward transform this. For example to impose a ceiling:

    .Select(s => TimeSpan.FromTicks(Math.Min(s.Ticks, yourChosenMaxDelay.Ticks)))

We can add to the documentation, to cover this.

**Comment by reisenberger** [comment] 2020-05-02 14:08
Fixed in #27, released as [v1.1.1](https://www.nuget.org/packages/Polly.Contrib.WaitAndRetry/1.1.1). Guidance [added to ReadMe](https://github.com/Polly-Contrib/Polly.Contrib.WaitAndRetry/blob/master/README.md#using-the-new-jitter-formula-with-a-large-number-of-retries).

**Closed by reisenberger** 2020-05-02 14:08 UTC
Labels: bug
